### ISSUE TITLE
Error on dict_conf.yaml

### ISSUE THREAD

**Issue by Xmaspro** [fanyingfx/lute-v3-fanyingfx#1]
**Description**
根据词典名称、地址，相应修改了dict_conf.yaml。启动程序后，出现以下错误：
yaml.scanner.ScannerError: mapping values are not allowed here
  in "/Users/.../Lute3/dict_conf.yaml", line 3, column 6

OS ：MacOS

烦请有空时看下，谢谢。

**Comment by fanyingfx** [comment]
可以提供一下你用的dict_conf.yaml文件吗

**Comment by Xmaspro** [comment]
> 可以提供一下你用的dict_conf.yaml文件吗

[dict_conf.yaml.zip](https://github.com/fanyingfx/lute-v3-fanyingfx/files/14818356/dict_conf.yaml.zip)

**Comment by fanyingfx** [comment]
rootfolder后面跟的是词典所在的最外层目录，还有因为是yaml，冒号后面需要加空格
```yaml
rootfolder: /Users/me/Library/Application Support/Lute3/Lute3/

dicts:
  English:
    dir_name: Eng 
    dict_list: 
      - olad4
      - MWnow
      - mwal
    pronunciation: null
  Japanese:
    dir_name: ja
    dict_list:
      - Shogakukanjcv3  
      - xsjrihanshuangjie
    pronunciation: nhk

```
